export const DropdownItems = {
  type: [
    { label: "Crankbaits", value: "Crankbaits" },
    { label: "Spinnerbaits", value: "Spinnerbaits" },
    { label: "PlasticWorms", value: "PlasticWorms" },
    { label: "TopwaterBaits", value: "TopwaterBaits" },
    { label: "Jigs", value: "Jigs" },
    { label: "Swimbaits", value: "Swimbaits" },
    { label: "Jerkbaits", value: "Jerkbaits" },
    { label: "TubeBaits", value: "TubeBaits" },
    { label: "Grubs", value: "Grubs" },
    { label: "Chatterbaits", value: "Chatterbaits" },
    { label: "Frogs", value: "Frogs" },
    { label: "Crawfish", value: "Crawfish" },
    {
      label: "SoftPlasticCreatureBaits",
      value: "SoftPlasticCreatureBaits",
    },
  ],
  season: [
    { label: "spring", value: "spring" },
    { label: "summer", value: "summer" },
    { label: "fall", value: "fall" },
    { label: "winter", value: "winter" },
  ],
  waterTemp: [
    { label: "38-40", value: "38-40" },
    { label: "40-42", value: "40-42" },
    { label: "42-44", value: "42-44" },
    { label: "44-46", value: "44-46" },
    { label: "46-48", value: "46-48" },
    { label: "48-50", value: "48-50" },
    { label: "50-52", value: "50-52" },
    { label: "52-54", value: "52-54" },
    { label: "54-56", value: "54-56" },
    { label: "56-58", value: "56-58" },
    { label: "58-60", value: "58-60" },
    { label: "60-62", value: "60-62" },
    { label: "62-64", value: "62-64" },
    { label: "64-66", value: "64-66" },
    { label: "66-68", value: "66-68" },
    { label: "68-70", value: "68-70" },
    { label: "70-72", value: "70-72" },
    { label: "72-74", value: "72-74" },
    { label: "74+", value: "74+" },
  ],
  timeOfDay: [
    { label: "Sunrise", value: "Sunrise" },
    { label: "Day", value: "Day" },
    { label: "Sunset", value: "Sunset" },
    { label: "Night", value: "Night" },
  ],
  waterClarity: [
    { label: "Clear", value: "Clear" },
    { label: "Stained", value: "Stained" },
    { label: "Dirty", value: "Dirty" },
  ],
  opacity: [
    { label: "Translucent or “ghost”", value: "Translucent or “ghost”" },
    { label: "Translucent or opaque", value: "Translucent or opaque" },
    { label: "Opaque", value: "Opaque" },
  ],
  wind: [
    { label: "0 MPH", value: "0 MPH" },
    { label: "5-10 MPH", value: "5-10 MPH" },
    { label: "10-15 MPH", value: "10-15 MPH" },
    { label: "15-20 MPH", value: "15-20 MPH" },
  ],
  depth: [
    { label: "0-9 Feet", value: "0-9 Feet" },
    { label: "10-12 Feet", value: "10-12 Feet" },
    { label: "12-20 Feet", value: "12-20 Feet" },
    { label: "20-35 Feet", value: "20-35 Feet" },
    { label: "35+ Feet", value: "35+ Feet" },
  ],
  weatherCondition: [
    { label: "Bright Sunny", value: "Bright Sunny" },
    { label: "Partly Cloudy", value: "Partly Cloudy" },
    { label: "Cloudy", value: "Cloudy" },
    { label: "Raining", value: "Raining" },
  ],
  structure: [
    { label: "Laydown & Brush", value: "Laydown & Brush" },
    { label: "Rocks", value: "Rocks" },
    { label: "Grass", value: "Grass" },
    { label: "Dams", value: "Dams" },
    { label: "Drop-offs", value: "Drop-offs" },
    { label: "Reffs", value: "Reffs" },
    { label: "Brush Piles", value: "Brush Piles" },
    { label: "Points", value: "Points" },
  ],
  behavior: [
    { label: "Skittish", value: "Skittish" },
    { label: "Lock Jaw", value: "Lock Jaw" },
    { label: "Suspended", value: "Suspended" },
    { label: "On the Move", value: "On the Move" },
    { label: "Hidden in Cover", value: "Hidden in Cover" },
  ],
  instruction: [
    { label: "Clear", value: "Clear" },
    { label: "Stained", value: "Stained" },
    { label: "Dirty", value: "Dirty" },
    { label: "General", value: "General" },
    { label: "Laydown & Brush", value: "Laydown & Brush" },
    { label: "Rocks", value: "Rocks" },
    { label: "Grass", value: "Grass" },
  ],
  current: [
    { label: "Yes", value: "Yes" },
    { label: "No", value: "No" },
  ],
  pattern: [
    { label: "Wake Baits", value: "Wake Baits" },
    { label: "Jerkbait", value: "Jerkbait" },
    { label: "Squarebill", value: "Squarebill" },
    { label: "Medium diving", value: "Medium diving" },
    { label: "Deep diving", value: "Deep diving" },
    { label: "Tight wobble", value: "Tight wobble" },
    { label: "Rattling", value: "Rattling" },
    { label: "Lipless", value: "Lipless" },
    { label: "Shallow diving", value: "Shallow diving" },
    { label: "Wide wobble", value: "Wide wobble" },
    { label: "Silent", value: "Silent" },
  ],
  line: [
    { label: "Braided", value: "Braided" },
    { label: "Monofilament", value: "Monofilament" },
    { label: "Fluorocarbon", value: "Fluorocarbon" },
    { label: "Copolymer", value: "Copolymer" },
  ],
  pound: [
    { label: "2-6 lb", value: "2-6 lb" },
    { label: "6-8 lb", value: "6-8 lb" },
    { label: "8-10 lb", value: "8-10 lb" },
    { label: "10-12 lb", value: "10-12 lb" },
    { label: "12-15 lb", value: "12-15 lb" },
    { label: "15-20 lb", value: "15-20 lb" },
  ],
};

export const Fields = [
  "type",
  "season",
  "waterTemp",
  "timeOfDay",
  "waterClarity",
  "opacity",
  "wind",
  "depth",
  "weatherCondition",
  "structure",
  "behavior",
  "instruction",
  "current",
  "pattern",
  "line",
  "pound",
];

export const TypeItems = {
  Crankbaits: [
    { label: "Lipless Crankbaits", value: "Lipless Crankbaits" },
    { label: "Diving Crankbaits", value: "Diving Crankbaits" },
    {
      label: "Shallow Running Crankbaits",
      value: "Shallow Running Crankbaits",
    },
    { label: "Medium Diving Crankbaits", value: "Medium Diving Crankbaits" },
    { label: "Deep Diving Crankbaits", value: "Deep Diving Crankbaits" },
    { label: "Rattle Traps", value: "Rattle Traps" },
    { label: "Squarebill Crankbaits", value: "Squarebill Crankbaits" },
    { label: "Lipless Rattle Traps", value: "Lipless Rattle Traps" },
    { label: "Jerkbaits", value: "Jerkbaits" },
    { label: "Minnow Crankbaits", value: "Minnow Crankbaits" },
    { label: "Stick baits", value: "Stick baits" },
    { label: "Blade baits", value: "Blade baits" },
    { label: "Flat-sided Crankbaits", value: "Flat-sided Crankbaits" },
    { label: "Bull Crankbait", value: "Bull Crankbait" },
    { label: "Wake baits", value: "Wake baits" },
  ],
  Spinnerbaits: [
    { label: "Tandem", value: "Tandem" },
    { label: "Colorado", value: "Colorado" },
    { label: "Willow leaf", value: "Willow leaf" },
    { label: "Indian Blade", value: "Indian Blade" },
    { label: "Buzzbait", value: "Buzzbait" },
    { label: "Inline", value: "Inline" },
    { label: "Spinnerbait jigs", value: "Spinnerbait jigs" },
    { label: "Spinnerbait Trailers", value: "Spinnerbait Trailers" },
  ],
  PlasticWorms: [
    { label: "Straight tail worms", value: "Straight tail worms" },
    { label: "Curly tail worms", value: "Curly tail worms" },
    { label: "Finesse worms", value: "Finesse worms" },
    { label: "Ribbon tail worms", value: "Ribbon tail worms" },
    { label: "Senko-style worms", value: "Senko-style worms" },
    { label: "Creature worms", value: "Creature worms" },
    { label: "Fluke-style worms", value: "Fluke-style worms" },
    { label: "Lizard worms", value: "Lizard worms" },
  ],
  TopwaterBaits: [
    { label: "Popper", value: "Popper" },
    { label: "Walking bait", value: "Walking bait" },
    { label: "Buzzbait", value: "Buzzbait" },
    { label: "Prop bait", value: "Prop bait" },
    { label: "Jitterbug", value: "Jitterbug" },
    { label: "Frog", value: "Frog" },
    { label: "Minnnow", value: "Minnnow" },
    { label: "Propeller Frog", value: "Propeller Frog" },
  ],
  Jigs: [
    { label: "Football Jig", value: "Football Jig" },
    { label: "Flipping Jig", value: "Flipping Jig" },
    { label: "Swim Jig", value: "Swim Jig" },
    { label: "Finesse Jig", value: "Finesse Jig" },
    { label: "Grass Jig", value: "Grass Jig" },
    { label: "Skippig Jig", value: "Skippig Jig" },
    { label: "Hair Jig", value: "Hair Jig" },
    { label: "Pitching Jig", value: "Pitching Jig" },
  ],
  Jerkbaits: [
    { label: "Suspending", value: "Suspending" },
    { label: "Floating", value: "Floating" },
    { label: "Sinking", value: "Sinking" },
    { label: "Lipless", value: "Lipless" },
    { label: "Long-casting", value: "Long-casting" },
    { label: "Slow-sinking", value: "Slow-sinking" },
    { label: "Fast-sinking", value: "Fast-sinking" },
    { label: "Jointed", value: "Jointed" },
  ],
  Crawfish: [
    { label: "Soft Plastic Craw", value: "Soft Plastic Craw" },
    { label: "Jig and Craw Trailer", value: "Jig and Craw Trailer" },
    { label: "Crankbait Craw", value: "Crankbait Craw" },
    { label: "Spinnerbait Craw", value: "Spinnerbait Craw" },
    { label: "Creature Bait", value: "Creature Bait" },
    { label: "Jig and Pig", value: "Jig and Pig" },
  ],
  SoftPlasticCreatureBaits: [
    { label: "Lizard", value: "Lizard" },
    { label: "Crawfish", value: "Crawfish" },
    { label: "Worm", value: "Worm" },
    { label: "Grub", value: "Grub" },
    { label: "Tube", value: "Tube" },
    { label: "Creature Bait", value: "Creature Bait" },
    { label: "Senko", value: "Senko" },
  ],
  Frogs: [
    { label: "Hollow Body", value: "Hollow Body" },
    { label: "Popping", value: "Popping" },
    { label: "Walking", value: "Walking" },
    { label: "Buzz", value: "Buzz" },
    { label: "Live Target", value: "Live Target" },
    { label: "Frog Trailer", value: "Frog Trailer" },
  ],
  Chatterbaits: [
    { label: "Bladed", value: "Bladed" },
    { label: "Double Willow Blade", value: "Double Willow Blade" },
    { label: "Swim Jig", value: "Swim Jig" },
    { label: "Trailerless", value: "Trailerless" },
    { label: "Finesse", value: "Finesse" },
    { label: "Heavy Cover", value: "Heavy Cover" },
    { label: "Vibrating Jig", value: "Vibrating Jig" },
  ],
  Grubs: [
    { label: "Twister Tail", value: "Twister Tail" },
    { label: "Paddle Tail", value: "Paddle Tail" },
    { label: "Straight Tail", value: "Straight Tail" },
    { label: "Tube Grub", value: "Tube Grub" },
    { label: "Hair Jig", value: "Hair Jig" },
    { label: "Flipping", value: "Flipping" },
    { label: "Swim", value: "Swim" },
    { label: "Finesse", value: "Finesse" },
  ],
  TubeBaits: [
    { label: "Solid", value: "Solid" },
    { label: "Hollow Body", value: "Hollow Body" },
    { label: "Finesse", value: "Finesse" },
    { label: "Saltwater", value: "Saltwater" },
    { label: "Crawfish", value: "Crawfish" },
    { label: "Goby", value: "Goby" },
    { label: "Grub", value: "Grub" },
    { label: "Creature", value: "Creature" },
  ],
  Swimbaits: [
    { label: "Paddle tial", value: "Paddle tial" },
    { label: "Glide baits", value: "Glide baits" },
    { label: "Jointed", value: "Jointed" },
    { label: "Curl tail", value: "Curl tail" },
    { label: "Boot tail", value: "Boot tail" },
    { label: "Swimbait grubs", value: "Swimbait grubs" },
    { label: "Hollow body", value: "Hollow body" },
    { label: "Shad-style", value: "Shad-style" },
    { label: "Jerk baits", value: "Jerk baits" },
  ],
};
