export const DropdownItems = {
  type: [
    { label: "Crankbaits", value: "Crankbaits" },
    { label: "Spinnerbaits", value: "Spinnerbaits" },
    { label: "Plastic worms", value: "Plastic worms" },
    { label: "Topwater baits", value: "Topwater baits" },
    { label: "Jigs", value: "Jigs" },
    { label: "Swimbaits", value: "Swimbaits" },
    { label: "Jerkbaits", value: "Jerkbaits" },
    { label: "Tube baits", value: "Tube baits" },
    { label: "Grubs", value: "Grubs" },
    { label: "Chatterbaits", value: "Chatterbaits" },
    { label: "Frogs", value: "Frogs" },
    { label: "Crawfish", value: "Crawfish" },
    {
      label: "Soft plastic creature baits",
      value: "Soft plastic creature baits",
    },
  ],
  season: [
    { label: "spring", value: "spring" },
    { label: "summer", value: "summer" },
    { label: "fall", value: "fall" },
    { label: "winter", value: "winter" },
  ],
  waterTemp: [
    { label: "38-40", value: "38-40" },
    { label: "40-42", value: "40-42" },
    { label: "42-44", value: "42-44" },
    { label: "44-46", value: "44-46" },
    { label: "46-48", value: "46-48" },
    { label: "48-50", value: "48-50" },
    { label: "50-52", value: "50-52" },
    { label: "52-54", value: "52-54" },
    { label: "54-56", value: "54-56" },
    { label: "56-58", value: "56-58" },
    { label: "58-60", value: "58-60" },
    { label: "60-62", value: "60-62" },
    { label: "62-64", value: "62-64" },
    { label: "64-66", value: "64-66" },
    { label: "66-68", value: "66-68" },
    { label: "68-70", value: "68-70" },
    { label: "70-72", value: "70-72" },
    { label: "72-74", value: "72-74" },
    { label: "74+", value: "74+" },
  ],
  timeOfDay: [
    { label: "Sunrise", value: "Sunrise" },
    { label: "Day", value: "Day" },
    { label: "Sunset", value: "Sunset" },
    { label: "Night", value: "Night" },
  ],
  waterClarity: [
    { label: "Clear", value: "Clear" },
    { label: "Stained", value: "Stained" },
    { label: "Dirty", value: "Dirty" },
  ],
  opacity: [
    { label: "Translucent or “ghost”", value: "Translucent or “ghost”" },
    { label: "Translucent or opaque", value: "Translucent or opaque" },
    { label: "Opaque", value: "Opaque" },
  ],
  wind: [
    { label: "0 MPH", value: "0 MPH" },
    { label: "5-10 MPH", value: "5-10 MPH" },
    { label: "10-15 MPH", value: "10-15 MPH" },
    { label: "15-20 MPH", value: "15-20 MPH" },
  ],
  depth: [
    { label: "0-9 Feet", value: "0-9 Feet" },
    { label: "10-12 Feet", value: "10-12 Feet" },
    { label: "12-20 Feet", value: "12-20 Feet" },
    { label: "20-35 Feet", value: "20-35 Feet" },
    { label: "35+ Feet", value: "35+ Feet" },
  ],
  weatherCondition: [
    { label: "Bright Sunny", value: "Bright Sunny" },
    { label: "Partly Cloudy", value: "Partly Cloudy" },
    { label: "Cloudy", value: "Cloudy" },
    { label: "Raining", value: "Raining" },
  ],
  structure: [
    { label: "Laydown & Brush", value: "Laydown & Brush" },
    { label: "Rocks", value: "Rocks" },
    { label: "Grass", value: "Grass" },
    { label: "Dams", value: "Dams" },
    { label: "Drop-offs", value: "Drop-offs" },
    { label: "Reffs", value: "Reffs" },
    { label: "Brush Piles", value: "Brush Piles" },
    { label: "Points", value: "Points" },
  ],
  behavior: [
    { label: "Skittish", value: "Skittish" },
    { label: "Lock Jaw", value: "Lock Jaw" },
    { label: "Suspended", value: "Suspended" },
    { label: "On the Move", value: "On the Move" },
    { label: "Hidden in Cover", value: "Hidden in Cover" },
  ],
  instruction: [
    { label: "Clear", value: "Clear" },
    { label: "Stained", value: "Stained" },
    { label: "Dirty", value: "Dirty" },
    { label: "General", value: "General" },
    { label: "Laydown & Brush", value: "Laydown & Brush" },
    { label: "Rocks", value: "Rocks" },
    { label: "Grass", value: "Grass" },
  ],
  current: [
    { label: "Yes", value: "Yes" },
    { label: "No", value: "No" },
  ],
  pattern: [
    { label: "Wake Baits", value: "Wake Baits" },
    { label: "Jerkbait", value: "Jerkbait" },
    { label: "Squarebill", value: "Squarebill" },
    { label: "Medium diving", value: "Medium diving" },
    { label: "Deep diving", value: "Deep diving" },
    { label: "Tight wobble", value: "Tight wobble" },
    { label: "Rattling", value: "Rattling" },
    { label: "Lipless", value: "Lipless" },
    { label: "Shallow diving", value: "Shallow diving" },
    { label: "Wide wobble", value: "Wide wobble" },
    { label: "Silent", value: "Silent" },
  ],
  line: [
    { label: "Braided", value: "Braided" },
    { label: "Monofilament", value: "Monofilament" },
    { label: "Fluorocarbon", value: "Fluorocarbon" },
    { label: "Copolymer", value: "Copolymer" },
  ],
  pound: [
    { label: "2-6 lb", value: "2-6 lb" },
    { label: "6-8 lb", value: "6-8 lb" },
    { label: "8-10 lb", value: "8-10 lb" },
    { label: "10-12 lb", value: "10-12 lb" },
    { label: "12-15 lb", value: "12-15 lb" },
    { label: "15-20 lb", value: "15-20 lb" },
  ],
};

export const Fields = [
  "type",
  "season",
  "waterTemp",
  "timeOfDay",
  "waterClarity",
  "opacity",
  "wind",
  "depth",
  "weatherCondition",
  "structure",
  "behavior",
  "instruction",
  "current",
  "pattern",
  "line",
  "pound",
];

export const TypeItems = {
  Crankbaits: [
    { label: "Lipless Crankbaits", value: "Lipless Crankbaits" },
    { label: "Diving Crankbaits", value: "Diving Crankbaits" },
    {
      label: "Shallow Running Crankbaits",
      value: "Shallow Running Crankbaits",
    },
    { label: "Medium Diving Crankbaits", value: "Medium Diving Crankbaits" },
    { label: "Deep Diving Crankbaits", value: "Deep Diving Crankbaits" },
    { label: "Rattle Traps", value: "Rattle Traps" },
    { label: "Squarebill Crankbaits", value: "Squarebill Crankbaits" },
    { label: "Lipless Rattle Traps", value: "Lipless Rattle Traps" },
    { label: "Jerkbaits", value: "Jerkbaits" },
    { label: "Minnow Crankbaits", value: "Minnow Crankbaits" },
    { label: "Stick baits", value: "Stick baits" },
    { label: "Blade baits", value: "Blade baits" },
    { label: "Flat-sided Crankbaits", value: "Flat-sided Crankbaits" },
    { label: "Bull Crankbait", value: "Bull Crankbait" },
    { label: "Wake baits", value: "Wake baits" },
  ],
  Spinnerbaits: [
    { label: "Single Blade Spinnerbaits", value: "Single Blade Spinnerbaits" },
    { label: "Double Blade Spinnerbaits", value: "Double Blade Spinnerbaits" },
    { label: "Chatterbaits", value: "Chatterbaits" },
    { label: "Buzzbaits", value: "Buzzbaits" },
    { label: "Bladed jigs", value: "Bladed jigs" },
    { label: "Inline Spinners", value: "Inline Spinners" },
    {
      label: "Colorado/Indiana Blade Spinnerbaits",
      value: "Colorado/Indiana Blade Spinnerbaits",
    },
    {
      label: "Willow-leaf Blade Spinnerbaits",
      value: "Willow-leaf Blade Spinnerbaits",
    },
    { label: "French Blade Spinnerbaits", value: "French Blade Spinnerbaits" },
    { label: "Triple Blade Spinnerbaits", value: "Triple Blade Spinnerbaits" },
    {
      label: "Skirt and Trailer combinations",
      value: "Skirt and Trailer combinations",
    },
    { label: "Offset Spinnerbaits", value: "Offset Spinnerbaits" },
    {
      label: "Silicone Skirts Spinnerbaits",
      value: "Silicone Skirts Spinnerbaits",
    },
    {
      label: "Football Head Spinnerbaits",
      value: "Football Head Spinnerbaits",
    },
    { label: "Flipping Spinnerbaits", value: "Flipping Spinnerbaits" },
  ],
};
